objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TECH_Waiting_Date_Max__c</fullName>
        <label>TECH_Waiting_Date_Max</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Nome de Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request_Action__c.object
<CustomObject>
    <fields>
        <fullName>New_Status__c</fullName>
        <label>New Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Actions</relationshipLabel>
        <relationshipName>Request_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Request Action</label>
    <nameField>
        <label>Request Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RequestTriggerHandler.cls
/******************************************************************
  |                       ***Accenture***
  |
  |Classe    : RequestTriggerHandler.cls
  |Data      : 16/04/2019
  |Descrição : Classe Handler referente à Criação ao Action.
  |
  ******************************************************************/
public class RequestTriggerHandler {

	//Método de Atualização de Status na Hora da Inserção 
	public static void insertStatusRequest() {

		Request_Action__c reqAction = new Request_Action__c();

		for (Request__c request : (List<Request__c>) Trigger.new ){
			if (request.Status__c != null || request.Status__c == null ) {
				request.Status__c = 'New';				
			}else{
                request.addError('Erro impossível atualizar o Status');
            }
		}
	}

	//Método de Atualizaçõa de Tech_Waiting_Date_Max 
	public static void updateTechWaiting(){
		
		final List<Request__c> ltReqAction = new List<Request__c>();
		
		for(Request_Action__c reqAction : (List<Request_Action__c>) Trigger.old){
			if(reqAction.New_Status__c == 'Waiting for User'){
				for(Request__c req : (List<Request__c>) Trigger.old){
					req.TECH_Waiting_Date_Max__c = Date.today();
					ltReqAction.add(req);
				}
				System.debug(reqAction);
			}else{
                reqAction.addError('Erro impossível atualizar o Status');
            }
		}
		update ltReqAction;
	
	}

	/*
	//Método de Atualizaçõa de Status 
	public static void updateStatusOfActforReq(){
	
	}
	*/
}