objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Nome de Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request_Action__c.object
<CustomObject>
    <fields>
        <fullName>New_Status__c</fullName>
        <label>New Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Actions</relationshipLabel>
        <relationshipName>Request_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Request Action</label>
    <nameField>
        <label>Request Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchupdateAllRequestTest.cls
@isTest
public class BatchupdateAllRequestTest {

    @isTest
    private static void BatAllReq(){
        
       
        
        List<Request__c> ltReq = new List<Request__c>();
        Request__c req = FactoryUtil.createRequest();
        ltReq.add(req);
        req.Status__c = 'Fix in progress';
        insert req;
        
        List<Request_Action__c> ltRequestAction = new List<Request_Action__c>();
        Request_Action__c reqAction = new Request_Action__c();
        insert reqAction;
        
        
        req.Status__c = 'Waiting for User';
        req.Date__c = Date.today();
        update req;
        
        ltRequestAction.add(reqAction);
        reqAction.New_Status__c = 'Waiting for User';
        update reqAction;
        
        
        Test.startTest();
        
        BatchupdateAllRequest btAllreq = new BatchupdateAllRequest();
        Database.executeBatch(btAllreq);
        
        Test.stopTest();
    }
    
}