objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TECH_Waiting_Date_Max__c</fullName>
        <label>TECH_Waiting_Date_Max</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time_average_per_Action__c</fullName>
        <label>Time average per Action</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_of_Actions__c</fullName>
        <label>Total of Actions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Request</fullName>
                </value>
                <value>
                    <fullName>Change Request</fullName>
                </value>
                <value>
                    <fullName>Defect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Nome de Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request_Action__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>New_Status__c</fullName>
        <label>New Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Actions</relationshipLabel>
        <relationshipName>Request_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Responsible__c</fullName>
        <label>Responsible</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Request Action</label>
    <nameField>
        <label>Request Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FactoryUtil.cls
/******************************************************************
  |                       ***Accenture***
  |
  |Classe    : FactoryUtil.cls
  |Autor	 : Victor Nascimento 
  |Descrição : Classe contendo métodos para acesso a inserção de valores.
  |
 *******************************************************************/
public class FactoryUtil {

	public static Request__c createRequest() {
		Request__c req = new Request__c(
		                                Type__c = 'New Request',
		                                Priority__c = 'Low',
		                                Date__c = Date.today(),
		                                TECH_Waiting_Date_Max__c = Date.today(),
		                                Status__c = 'New',
		                                Description__c = 'test',
		                                Total_of_Actions__c = 5,
		                                Time_average_per_Action__c = 5
		);

		return req;
	}
    public static Request_Action__c createRequestAction(){
        Request_Action__c reqAction = new Request_Action__c(
				Description__c = 'It was closed by system.',
				Data__c = Date.today(),
				Responsible__c = 'test',
				New_Status__c = 'Closed'
			);
        
        return reqAction; 
        
    }

}