objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Nome de Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request_Action__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>New_Status__c</fullName>
        <label>New Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Request Actions</relationshipLabel>
        <relationshipName>Request_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Responsible__c</fullName>
        <label>Responsible</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Request Action</label>
    <nameField>
        <label>Request Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchupdateAllRequest.cls
/******************************************************************
  |                       ***Accenture***
  |
  |Classe    : BatchupdateAllRequest.cls
  |Data      : 17/04/2019
  |Descrição : Classe Batch que faz a atualização dos Request.
  |
  ******************************************************************/
public class BatchupdateAllRequest implements Database.Batchable<sObject> {
  
    public Database.QueryLocator start(Database.BatchableContext bC) {
         
        String query = 'SELECT Id, Status__c FROM Request__c';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bC, List<Request__c> reqList) {
    
	 final List<Request__c> reqList_atual = new List<Request__c>();

        try {
        for(Request__c req : reqList)
        {        
            If(req.Status__c == 'Waiting for User' && req.Date__c <= Date.today()){
                req.Status__c = 'Canceled';
            }
			reqList_atual.add(req); // Update the Account Record
			  
		}
        update reqList_atual;
		System.debug('update o reqList_atual' + reqList_atual);

		Request_Action__c reqAction = new Request_Action__c(
				Description__c = 'It was closed by system.',
				Data__c = Date.today(),
				Responsible__c = reqList_atual[0].Responsible__c,
				New_Status__c = 'Closed'
			);
			insert reqAction; 
			System.debug('Inserindo o reqAction' + reqAction);


        } catch(Exception e) {
		    System.debug('Falhou o Batch');
		    System.debug(e);
        }
         
    }   
     
    public void finish(Database.BatchableContext bC) {
        // execute any post-processing operations
		System.debug(bC);
  }
}