objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Nome de Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ActionRequestController.cls
/******************************************************************
  |                       ***Accenture***
  |
  |Classe    : ActionRequestController.cls
  |Data      : 15/04/2019
  |Descrição : Classe controladora do componente referente à Criação de ActionSupport.
  |
  ******************************************************************/

public with sharing class ActionRequestController {

	@AuraEnabled
	public static Map<String, Object> getRequests(String recordId) {
		Map<String, Object> dataReturn = new Map<String, Object> ();
		
		List<Request__c> ltRequest = [SELECT Id, Name, Date__c, Description__c, Status__c FROM Request__c WHERE id = : recordId];
		if(!ltRequest.isEmpty()){
			dataReturn.put('req', ltRequest);
			dataReturn.put('status', 'success');
		}else{
			dataReturn.put('status', 'error');
			dataReturn.put('nulo', null);
		}		
		return dataReturn;
	}

}