objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Fix in progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waiting for User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Nome de Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Util.cls
/******************************************************************
|                       ***Accenture***
|
|Classe    : Util.cls
|Autor	 : Victor Nascimento 
|Descrição : Classe contendo métodos para acesso a base.
|
*******************************************************************/

public with sharing class Util {
    
    private static Map<String, Map<String, Id>> fRecTypes = new Map<String, Map<String, Id>> ();
    private static Map<Id, RecordType> lMap;
    
    static {
        lMap = new Map<Id, RecordType> ([select id, RecordType.Name, SobjectType, DeveloperName from RecordType WHERE IsActive = true]);
        
        for (RecordType lRec : lMap.values()) {
            
            Map<String, Id> lObjMap = fRecTypes.get(lRec.SobjectType);
            
            if (lObjMap == null) {
                lObjMap = new Map<String, Id> ();
                fRecTypes.put(lRec.SobjectType, lObjMap);
            }
            lObjMap.put(lRec.DeveloperName, lRec.id);
        }
    }
	//Pegando a Lista de Requisição 
	public static List<Request__c> getlistRequestRecord(String recordId){
		return[SELECT Id, Name, Date__c, Description__c, Status__c FROM Request__c WHERE id = : recordId];
	}


}